apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: testimage-choigonyok
  namespace: test-system
spec:
  containers:
  - env:
    - name: TEST_KEY
      valueFrom:
        secretKeyRef:
          key: TEST_KEY
          name: secret-choigonyok
    image: ci.choigonyok.com:8080/test-system/testimage:testversion
    name: testimage-choigonyok
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /configmap-choigonyok
      name: configmap-choigonyok
  imagePullSecrets:
  - name: harborcred
  volumes:
  - configMap:
      items:
      - key: nginx.conf
        path: etc/nginx/test.conf
      name: configmap-choigonyok
    name: configmap-choigonyok
status: {}
